import type { SingleEliminationProps } from "$lib";

export default {
	rounds: [
		{ roundId: 1, roundName: "Round of 32" },
		{ roundId: 2, roundName: "Round of 16" },
		{ roundId: 3, roundName: "Quarterfinals" },
		{ roundId: 4, roundName: "Semifinals" },
		{ roundId: 5, roundName: "Grand Finals" },
	],
	matches: [
		// Round of 32 (16 matches)
		{
			matchId: 1,
			roundId: 1,
			entrant1: { entrantId: 1, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 2, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 2,
			roundId: 1,
			entrant1: { entrantId: 3, entrantScore: 0, entrantStatus: "LOST" },
			entrant2: { entrantId: 4, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 3,
			roundId: 1,
			entrant1: { entrantId: 5, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 6, entrantScore: 1, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 4,
			roundId: 1,
			entrant1: { entrantId: 7, entrantScore: 2, entrantStatus: "LOST" },
			entrant2: { entrantId: 8, entrantScore: 3, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 5,
			roundId: 1,
			entrant1: { entrantId: 9, entrantScore: 2, entrantStatus: "WON" },
			entrant2: { entrantId: 10, entrantScore: 0, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 6,
			roundId: 1,
			entrant1: { entrantId: 11, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 12, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 7,
			roundId: 1,
			entrant1: { entrantId: 13, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 14, entrantScore: 2, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 8,
			roundId: 1,
			entrant1: { entrantId: 15, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 16, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 9,
			roundId: 1,
			entrant1: { entrantId: 17, entrantScore: 2, entrantStatus: "WON" },
			entrant2: { entrantId: 18, entrantScore: 0, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 10,
			roundId: 1,
			entrant1: { entrantId: 19, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 20, entrantScore: 1, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 11,
			roundId: 1,
			entrant1: { entrantId: 21, entrantScore: 2, entrantStatus: "LOST" },
			entrant2: { entrantId: 22, entrantScore: 3, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 12,
			roundId: 1,
			entrant1: { entrantId: 23, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 24, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 13,
			roundId: 1,
			entrant1: { entrantId: 25, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 26, entrantScore: 2, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 14,
			roundId: 1,
			entrant1: { entrantId: 27, entrantScore: 0, entrantStatus: "LOST" },
			entrant2: { entrantId: 28, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 15,
			roundId: 1,
			entrant1: { entrantId: 29, entrantScore: 2, entrantStatus: "WON" },
			entrant2: { entrantId: 30, entrantScore: 1, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 16,
			roundId: 1,
			entrant1: { entrantId: 31, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 32, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},

		// Round of 16 (8 matches)
		{
			matchId: 17,
			roundId: 2,
			entrant1: { entrantId: 2, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 4, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 18,
			roundId: 2,
			entrant1: { entrantId: 5, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 8, entrantScore: 2, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 19,
			roundId: 2,
			entrant1: { entrantId: 9, entrantScore: 2, entrantStatus: "WON" },
			entrant2: { entrantId: 12, entrantScore: 1, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 20,
			roundId: 2,
			entrant1: { entrantId: 13, entrantScore: 0, entrantStatus: "LOST" },
			entrant2: { entrantId: 16, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 21,
			roundId: 2,
			entrant1: { entrantId: 17, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 19, entrantScore: 2, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 22,
			roundId: 2,
			entrant1: { entrantId: 22, entrantScore: 2, entrantStatus: "LOST" },
			entrant2: { entrantId: 24, entrantScore: 3, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 23,
			roundId: 2,
			entrant1: { entrantId: 25, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 28, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 24,
			roundId: 2,
			entrant1: { entrantId: 29, entrantScore: 0, entrantStatus: "LOST" },
			entrant2: { entrantId: 32, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},

		// Quarterfinals (4 matches)
		{
			matchId: 25,
			roundId: 3,
			entrant1: { entrantId: 4, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 5, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 26,
			roundId: 3,
			entrant1: { entrantId: 9, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 16, entrantScore: 2, entrantStatus: "LOST" },
			status: "DONE",
		},
		{
			matchId: 27,
			roundId: 3,
			entrant1: { entrantId: 17, entrantScore: 2, entrantStatus: "LOST" },
			entrant2: { entrantId: 24, entrantScore: 3, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 28,
			roundId: 3,
			entrant1: { entrantId: 28, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 32, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},

		// Semifinals (2 matches)
		{
			matchId: 29,
			roundId: 4,
			entrant1: { entrantId: 5, entrantScore: 0, entrantStatus: "LOST" },
			entrant2: { entrantId: 9, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},
		{
			matchId: 30,
			roundId: 4,
			entrant1: { entrantId: 24, entrantScore: 1, entrantStatus: "LOST" },
			entrant2: { entrantId: 32, entrantScore: 2, entrantStatus: "WON" },
			status: "DONE",
		},

		// Grand Finals
		{
			matchId: 31,
			roundId: 5,
			entrant1: { entrantId: 9, entrantScore: 3, entrantStatus: "WON" },
			entrant2: { entrantId: 32, entrantScore: 2, entrantStatus: "LOST" },
			status: "DONE",
		},
	],
	entrants: [
		{ entrantId: 1, entrantName: "Thunder Wolves" },
		{ entrantId: 2, entrantName: "Sky Knights" },
		{ entrantId: 3, entrantName: "Dragon Fury" },
		{ entrantId: 4, entrantName: "Phoenix Blaze" },
		{ entrantId: 5, entrantName: "Ice Giants" },
		{ entrantId: 6, entrantName: "Shadow Hunters" },
		{ entrantId: 7, entrantName: "Solar Flares" },
		{ entrantId: 8, entrantName: "Lunar Eclipse" },
		{ entrantId: 9, entrantName: "Storm Riders" },
		{ entrantId: 10, entrantName: "Titan Warriors" },
		{ entrantId: 11, entrantName: "Vortex Vipers" },
		{ entrantId: 12, entrantName: "Crimson Hawks" },
		{ entrantId: 13, entrantName: "Mystic Dragons" },
		{ entrantId: 14, entrantName: "Galactic Guardians" },
		{ entrantId: 15, entrantName: "Iron Clad" },
		{ entrantId: 16, entrantName: "Night Stalkers" },
		{ entrantId: 17, entrantName: "Blaze Brigade" },
		{ entrantId: 18, entrantName: "Frost Witches" },
		{ entrantId: 19, entrantName: "Sea Serpents" },
		{ entrantId: 20, entrantName: "Desert Nomads" },
		{ entrantId: 21, entrantName: "Thunder Hawks" },
		{ entrantId: 22, entrantName: "Cosmic Crusaders" },
		{ entrantId: 23, entrantName: "Dark Matter" },
		{ entrantId: 24, entrantName: "Light Bringers" },
		{ entrantId: 25, entrantName: "Neon Ninjas" },
		{ entrantId: 26, entrantName: "Cyber Samurai" },
		{ entrantId: 27, entrantName: "Atomic Alloys" },
		{ entrantId: 28, entrantName: "Gravity Giants" },
		{ entrantId: 29, entrantName: "Plasma Phantoms" },
		{ entrantId: 30, entrantName: "Sonic Striders" },
		{ entrantId: 31, entrantName: "Terra Titans" },
		{ entrantId: 32, entrantName: "Celestial Sentinels" },
	],
} as SingleEliminationProps;
